<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';
$pageTitle='Jaipur Taxi Booking & Rajasthan Cabs | Swiggy Wala';
$pageDescription='Book Jaipur airport transfers, local taxis, one-way and round-trip Rajasthan cabs with Swiggy Wala. Send your route and travel date for booking assistance.';
include 'includes/header.php';
$data=require 'data/site-data.php';
$blogs=require 'data/blogs.php';
$locations=require 'data/locations.php';
$source='homepage';
$compact=true;
?>
<main>
<section class="hero sw-taxi-hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Jaipur taxi & Rajasthan cabs</span><h1>Book your taxi. <span>Travel Rajasthan your way.</span></h1><p>Airport pickup, Jaipur local taxi, one-way outstation, round trip or multi-city travel—send your route and date and our team can confirm the ride with you.</p><div class="hero-actions"><a class="btn" href="#taxi-booking">Book a Taxi</a><a class="btn btn-outline" href="<?= e(wa_link('Hello Swiggy Wala, I want to book a taxi.')) ?>" target="_blank" rel="noopener">WhatsApp</a></div><div class="trust-row"><span>Airport transfer</span><span>Jaipur local</span><span>Outstation cabs</span></div></div><div id="taxi-booking" class="sw-booking-card"><div class="sw-booking-card-head"><span>Taxi request</span><h2>Where do you want to go?</h2><p>Share the trip details. No online payment is taken on this form.</p></div><?php require __DIR__ . '/partials/booking-form.php'; ?></div></div></section>

<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Taxi services</span><h2>Start with the ride you need.</h2></div><p>Taxi booking is the primary service. Rajasthan tours and travel planning remain available as supporting services.</p></div><div class="cards"><article class="card service-card-visual"><div class="card-content"><span class="eyebrow">Airport</span><h3>Jaipur Airport Transfer</h3><p>Request airport pickup or drop with date, time and route details captured in advance.</p><a class="text-link" href="/booking.php?trip=airport">Book airport taxi →</a></div></article><article class="card service-card-visual"><div class="card-content"><span class="eyebrow">Local</span><h3>Jaipur Local Taxi</h3><p>Point-to-point and local cab requirements across Jaipur for personal or business travel.</p><a class="text-link" href="/booking.php?trip=local">Book local taxi →</a></div></article><article class="card service-card-visual"><div class="card-content"><span class="eyebrow">Outstation</span><h3>One Way & Round Trip</h3><p>Send pickup, destination and dates for intercity cab requirements across Rajasthan and beyond.</p><a class="text-link" href="/booking.php?trip=outstation">Request outstation cab →</a></div></article></div></div></section>

<section class="section section-soft"><div class="container"><div class="section-head"><div><span class="eyebrow">Multi-page travel website</span><h2>Taxi booking first, complete travel support behind it.</h2></div><p>Explore separate pages for services, destinations, packages, Jaipur locations, travel guides and company information.</p></div><div class="cards"><article class="card"><div class="card-content"><h3>Services</h3><p>Taxi, transfer, tours and supporting travel services.</p><a class="text-link" href="/services.php">View services →</a></div></article><article class="card"><div class="card-content"><h3>Destinations</h3><p>Explore Rajasthan cities and route ideas.</p><a class="text-link" href="/destinations.php">Explore destinations →</a></div></article><article class="card"><div class="card-content"><h3>Tour Packages</h3><p>Use an existing package as a base for a Rajasthan trip.</p><a class="text-link" href="/packages.php">View packages →</a></div></article></div></div></section>

<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Popular destinations</span><h2>Turn the taxi into a complete Rajasthan trip.</h2></div><p>Need more than a ride? Explore well-paced routes through Rajasthan’s most requested cities.</p></div><div class="cards"><?php foreach(array_slice($data['destinations'],0,3) as $d):?><article class="card"><div class="image-placeholder" style="background-image:url('/<?= e($d['image']) ?>')"></div><div class="card-content"><div class="card-meta"><span><?= e($d['days']) ?></span><span>Rajasthan</span></div><h3><?= e($d['name']) ?></h3><p><?= e($d['tag']) ?></p><a class="text-link" href="/destinations.php#<?= e($d['slug']) ?>">Explore destination →</a></div></article><?php endforeach;?></div></div></section>

<section class="section section-soft"><div class="container"><div class="section-head"><div><span class="eyebrow">Jaipur branch network</span><h2>Local booking support across Jaipur.</h2></div><p>Choose a nearby location for taxi, tour and trip-planning assistance.</p></div><div class="locations-grid locations-grid-home"><?php foreach($locations as $loc):?><article class="location-card location-card-compact"><div class="location-card-body"><span class="eyebrow"><?= e($loc['area']) ?></span><h3><?= e($loc['short_name']) ?></h3><p class="location-address"><?= e($loc['address']) ?></p><div class="location-actions"><a class="btn btn-small" href="/locations/<?= e($loc['slug']) ?>.php">Branch details</a><a class="btn btn-small btn-outline" href="<?= e($loc['maps_url']) ?>" target="_blank" rel="noopener">Directions</a></div></div></article><?php endforeach;?></div><div class="center-action"><a class="text-link" href="/locations.php">Explore all Jaipur locations →</a></div></div></section>

<section class="section"><div class="container"><div class="sw-taxi-cta"><div><span class="eyebrow">Need a cab?</span><h2>Send your route and travel date now.</h2><p>Your request goes directly into the lead panel for booking follow-up.</p></div><div class="d-flex gap-2 flex-wrap"><a class="sw-btn" href="/booking.php">Book Taxi</a><a class="sw-btn-outline" href="tel:<?= e(PHONE_TEL) ?>">Call <?= e(PHONE_DISPLAY) ?></a></div></div></div></section>
</main>
<?php include 'includes/footer.php';?>
