<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';
sw_require_admin();
$pdo = sw_db();
$allowedStatuses = ['new','contacted','quoted','confirmed','completed','cancelled'];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!sw_verify_csrf($_POST['csrf_token'] ?? null)) { http_response_code(400); exit('Invalid CSRF token'); }
    $id = (int)($_POST['lead_id'] ?? 0); $status = (string)($_POST['status'] ?? '');
    if ($id > 0 && in_array($status, $allowedStatuses, true)) {
        $stmt = $pdo->prepare('UPDATE leads SET status = ? WHERE id = ?'); $stmt->execute([$status, $id]);
    }
    header('Location: /admin/?' . http_build_query(['status' => $_GET['status'] ?? '', 'q' => $_GET['q'] ?? ''])); exit;
}
$status = trim((string)($_GET['status'] ?? ''));
$q = trim((string)($_GET['q'] ?? ''));
$where = []; $params = [];
if ($status !== '' && in_array($status, $allowedStatuses, true)) { $where[] = 'status = ?'; $params[] = $status; }
if ($q !== '') { $where[] = '(reference LIKE ? OR name LIKE ? OR phone LIKE ? OR pickup LIKE ? OR dropoff LIKE ?)'; $like = '%' . $q . '%'; array_push($params, $like,$like,$like,$like,$like); }
$sql = 'SELECT * FROM leads' . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY created_at DESC LIMIT 100';
$stmt = $pdo->prepare($sql); $stmt->execute($params); $leads = $stmt->fetchAll();
$stats = array_fill_keys($allowedStatuses, 0);
foreach ($pdo->query('SELECT status, COUNT(*) total FROM leads GROUP BY status') as $row) { if (isset($stats[$row['status']])) $stats[$row['status']] = (int)$row['total']; }
$total = array_sum($stats);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Taxi Leads | Swiggy Wala</title><link rel="stylesheet" href="/main-home/assets/css/bootstrap.min.css"><link rel="stylesheet" href="/main-home/assets/css/bootstrap-icons.css"><link rel="stylesheet" href="/assets/css/app.css"></head><body class="sw-admin-body"><header class="sw-admin-top"><div class="container-fluid d-flex justify-content-between align-items-center"><div><strong>Swiggy Wala</strong><span> Lead Panel</span></div><div class="d-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="/">Website</a><form method="post" action="/admin/logout.php"><input type="hidden" name="csrf_token" value="<?= sw_e(sw_csrf_token()) ?>"><button class="btn btn-sm btn-dark" type="submit">Logout</button></form></div></div></header><main class="container-fluid py-4"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="h3 mb-1">Taxi booking leads</h1><p class="text-muted mb-0">Newest 100 matching leads are shown.</p></div><a class="btn btn-outline-primary" href="/admin/export.php?<?= sw_e(http_build_query(['status'=>$status,'q'=>$q])) ?>"><i class="bi bi-download"></i> Export CSV</a></div><div class="row g-3 mb-4"><div class="col-6 col-md-3 col-xl-2"><div class="sw-stat"><span>Total</span><strong><?= $total ?></strong></div></div><?php foreach (['new','contacted','confirmed','completed','cancelled'] as $s): ?><div class="col-6 col-md-3 col-xl-2"><div class="sw-stat"><span><?= sw_e(ucfirst($s)) ?></span><strong><?= $stats[$s] ?></strong></div></div><?php endforeach; ?></div>
<div class="sw-admin-card mb-4"><form class="row g-2" method="get"><div class="col-md-7"><input class="form-control" name="q" value="<?= sw_e($q) ?>" placeholder="Search reference, name, phone, pickup or destination"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><?php foreach ($allowedStatuses as $s): ?><option value="<?= sw_e($s) ?>" <?= $status===$s?'selected':'' ?>><?= sw_e(ucfirst($s)) ?></option><?php endforeach; ?></select></div><div class="col-md-2 d-grid"><button class="btn btn-primary">Filter</button></div></form></div>
<div class="sw-admin-card p-0 overflow-hidden"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Lead</th><th>Trip</th><th>Route</th><th>Travel</th><th>Contact</th><th>Status</th></tr></thead><tbody><?php if (!$leads): ?><tr><td colspan="6" class="text-center py-5 text-muted">No leads found.</td></tr><?php endif; ?><?php foreach ($leads as $lead): ?><tr><td><strong><?= sw_e($lead['reference']) ?></strong><br><small class="text-muted"><?= sw_e(date('d M Y, h:i A', strtotime($lead['created_at']))) ?></small><br><small><?= sw_e($lead['source']) ?></small></td><td><strong><?= sw_e($lead['trip_type']) ?></strong><br><small><?= sw_e($lead['vehicle'] ?: 'Any vehicle') ?> · <?= (int)$lead['passengers'] ?> pax</small></td><td><strong><?= sw_e($lead['pickup']) ?></strong><br><span class="text-muted">to <?= sw_e($lead['dropoff']) ?></span><?php if ($lead['notes']): ?><br><small class="text-muted"><?= sw_e(mb_strimwidth($lead['notes'],0,90,'…')) ?></small><?php endif; ?></td><td><?= sw_e(date('d M Y', strtotime($lead['pickup_date']))) ?><?php if ($lead['pickup_time']): ?><br><small><?= sw_e(substr($lead['pickup_time'],0,5)) ?></small><?php endif; ?><?php if ($lead['return_date']): ?><br><small>Return <?= sw_e(date('d M', strtotime($lead['return_date']))) ?></small><?php endif; ?></td><td><strong><?= sw_e($lead['name']) ?></strong><br><a href="tel:<?= sw_e(preg_replace('/\D+/','',$lead['phone'])) ?>"><?= sw_e($lead['phone']) ?></a><?php if ($lead['email']): ?><br><small><?= sw_e($lead['email']) ?></small><?php endif; ?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= sw_e(sw_csrf_token()) ?>"><input type="hidden" name="lead_id" value="<?= (int)$lead['id'] ?>"><select class="form-select form-select-sm sw-status" name="status" onchange="this.form.submit()"><?php foreach ($allowedStatuses as $s): ?><option value="<?= sw_e($s) ?>" <?= $lead['status']===$s?'selected':'' ?>><?= sw_e(ucfirst($s)) ?></option><?php endforeach; ?></select></form></td></tr><?php endforeach; ?></tbody></table></div></div></main></body></html>
